/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.esm;

import org.springframework.stereotype.Component;

@Component
public class App {
    public static void main(String[] args) {
        Library library = new Library();
        library.startApplication();
    }
}
